-- ═══════════════════════════════════════════════════════
-- Business Dashboard — Full Database Setup
-- ═══════════════════════════════════════════════════════
-- Run this in your Supabase SQL Editor (Database > SQL Editor).
-- Creates all tables needed for every module.
-- Safe to re-run — uses IF NOT EXISTS throughout.


-- ───────────────────────────────────────────────────────
-- TASKS MODULE: Kanban board
-- ───────────────────────────────────────────────────────

-- Main kanban board tasks with drag-and-drop columns
CREATE TABLE IF NOT EXISTS kanban_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL DEFAULT 'todo'
    CHECK (status IN ('todo', 'in_progress', 'review', 'done')),
  label TEXT DEFAULT 'content'
    CHECK (label IN ('content', 'dev', 'design', 'urgent')),
  assigned_to TEXT,
  assigned_to_initials TEXT,
  created_by TEXT,
  position INTEGER DEFAULT 0,
  due_date TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

-- In-app notifications (task assignments, system alerts)
CREATE TABLE IF NOT EXISTS notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_initials TEXT NOT NULL,
  type TEXT NOT NULL DEFAULT 'task_assigned',
  title TEXT NOT NULL,
  message TEXT,
  read BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);


-- ───────────────────────────────────────────────────────
-- COMPETITORS MODULE: Competitor intelligence
-- ───────────────────────────────────────────────────────

-- Tracked competitor accounts (Instagram handles)
CREATE TABLE IF NOT EXISTS competitors (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  instagram_handle TEXT NOT NULL UNIQUE,
  display_name TEXT,
  profile_pic_url TEXT,
  color TEXT DEFAULT '#635bff',
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Individual posts scraped from competitor accounts
-- Populated by Apify scraping jobs
CREATE TABLE IF NOT EXISTS competitor_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  handle TEXT NOT NULL,
  content TEXT,
  likes INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  views INTEGER DEFAULT 0,
  post_url TEXT UNIQUE,
  thumbnail_url TEXT,
  posted_at TIMESTAMPTZ,
  scraped_at TIMESTAMPTZ DEFAULT now()
);


-- ───────────────────────────────────────────────────────
-- CONTENT MODULE: Your own posts + analytics
-- ───────────────────────────────────────────────────────

-- Your own Instagram posts (pulled via IG Graph API)
CREATE TABLE IF NOT EXISTS client_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ig_media_id TEXT UNIQUE,
  post_url TEXT,
  content TEXT,
  media_type TEXT,
  thumbnail_url TEXT,
  likes INTEGER DEFAULT 0,
  comments INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  views INTEGER DEFAULT 0,
  reach INTEGER DEFAULT 0,
  saved INTEGER DEFAULT 0,
  posted_at TIMESTAMPTZ,
  pulled_at TIMESTAMPTZ DEFAULT now()
);

-- AI-generated content ideas (from competitor analysis + trends)
CREATE TABLE IF NOT EXISTS content_ideas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  hook TEXT NOT NULL,
  format TEXT,
  pillar TEXT,
  angle TEXT,
  status TEXT DEFAULT 'pending'
    CHECK (status IN ('pending', 'scripted', 'scheduled', 'published', 'rejected')),
  scheduled_for TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Scripts written for content ideas
CREATE TABLE IF NOT EXISTS scripts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  idea_id UUID REFERENCES content_ideas(id) ON DELETE SET NULL,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  estimated_seconds INTEGER,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Posts scheduled for publishing
CREATE TABLE IF NOT EXISTS scheduled_posts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  idea_id UUID REFERENCES content_ideas(id) ON DELETE SET NULL,
  script_id UUID REFERENCES scripts(id) ON DELETE SET NULL,
  platform TEXT,
  status TEXT DEFAULT 'queued'
    CHECK (status IN ('queued', 'published', 'failed')),
  scheduled_for TIMESTAMPTZ,
  published_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT now()
);


-- ───────────────────────────────────────────────────────
-- HOOKS MODULE: Viral hook extraction + templates
-- ───────────────────────────────────────────────────────

-- Extracted hooks from top-performing posts (yours + competitors)
-- Populated by transcribing reels and extracting the opening line
CREATE TABLE IF NOT EXISTS post_hooks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  post_url TEXT UNIQUE,
  handle TEXT,
  is_own BOOLEAN DEFAULT false,
  hook_text TEXT NOT NULL,
  full_transcript TEXT,
  views INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  shares INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Reusable hook templates generated by AI from top hooks
-- Templates use [PLACEHOLDERS] for fill-in-the-blank reuse
CREATE TABLE IF NOT EXISTS hook_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  template TEXT NOT NULL,
  example_hook TEXT,
  example_handle TEXT,
  views INTEGER DEFAULT 0,
  score INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now()
);


-- ───────────────────────────────────────────────────────
-- SCHEDULING MODULE: Drive-to-social pipeline
-- ───────────────────────────────────────────────────────

-- Content queue: videos detected in Google Drive, pending scheduling
-- Each item tracks the full lifecycle: detected → captioned → scheduled
CREATE TABLE IF NOT EXISTS content_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT,
  drive_file_id TEXT UNIQUE,
  drive_file_name TEXT,
  drive_file_url TEXT,
  thumbnail_url TEXT,
  transcript TEXT,
  suggested_caption TEXT,
  caption TEXT,
  youtube_title TEXT,
  status TEXT DEFAULT 'ready'
    CHECK (status IN ('ready', 'processing', 'scheduled', 'failed')),
  platforms TEXT[],
  scheduled_for TIMESTAMPTZ,
  media_url TEXT,
  is_trial_reel BOOLEAN DEFAULT false,
  zernio_post_ids JSONB,
  error TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);


-- ───────────────────────────────────────────────────────
-- EMAIL MODULE: Gmail AI triage cache
-- ───────────────────────────────────────────────────────

-- Cached email triage results so we don't re-process emails
CREATE TABLE IF NOT EXISTS email_triage (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  gmail_id TEXT NOT NULL UNIQUE,
  thread_id TEXT,
  subject TEXT,
  sender_name TEXT,
  sender_email TEXT,
  snippet TEXT,
  full_body TEXT,
  priority TEXT
    CHECK (priority IN ('high', 'medium', 'low', 'filtered')),
  category TEXT,
  received_at TIMESTAMPTZ,
  triaged_at TIMESTAMPTZ DEFAULT now()
);


-- ───────────────────────────────────────────────────────
-- FINANCIALS MODULE: Revenue goals
-- ───────────────────────────────────────────────────────

-- Monthly financial goals with progress tracking
-- auto_sync goals pull current value from Stripe automatically
CREATE TABLE IF NOT EXISTS financial_goals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  target NUMERIC NOT NULL DEFAULT 0,
  current NUMERIC NOT NULL DEFAULT 0,
  month TEXT NOT NULL,
  auto_sync BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- Weekly objectives with progress bars
CREATE TABLE IF NOT EXISTS objectives (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  target NUMERIC NOT NULL DEFAULT 0,
  current NUMERIC NOT NULL DEFAULT 0,
  week_start TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);


-- ───────────────────────────────────────────────────────
-- ROW LEVEL SECURITY
-- ───────────────────────────────────────────────────────
-- Enable RLS on all tables. The default policy allows all
-- authenticated users full access. Tighten these policies
-- if you need per-user isolation.

ALTER TABLE kanban_tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitors ENABLE ROW LEVEL SECURITY;
ALTER TABLE competitor_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE client_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_ideas ENABLE ROW LEVEL SECURITY;
ALTER TABLE scripts ENABLE ROW LEVEL SECURITY;
ALTER TABLE scheduled_posts ENABLE ROW LEVEL SECURITY;
ALTER TABLE post_hooks ENABLE ROW LEVEL SECURITY;
ALTER TABLE hook_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE content_queue ENABLE ROW LEVEL SECURITY;
ALTER TABLE email_triage ENABLE ROW LEVEL SECURITY;
ALTER TABLE financial_goals ENABLE ROW LEVEL SECURITY;
ALTER TABLE objectives ENABLE ROW LEVEL SECURITY;

-- Allow all authenticated users full access (default open policy)
-- Replace these with stricter policies if you have multiple users
CREATE POLICY "auth_all" ON kanban_tasks FOR ALL USING (true);
CREATE POLICY "auth_all" ON notifications FOR ALL USING (true);
CREATE POLICY "auth_all" ON competitors FOR ALL USING (true);
CREATE POLICY "auth_all" ON competitor_posts FOR ALL USING (true);
CREATE POLICY "auth_all" ON client_posts FOR ALL USING (true);
CREATE POLICY "auth_all" ON content_ideas FOR ALL USING (true);
CREATE POLICY "auth_all" ON scripts FOR ALL USING (true);
CREATE POLICY "auth_all" ON scheduled_posts FOR ALL USING (true);
CREATE POLICY "auth_all" ON post_hooks FOR ALL USING (true);
CREATE POLICY "auth_all" ON hook_templates FOR ALL USING (true);
CREATE POLICY "auth_all" ON content_queue FOR ALL USING (true);
CREATE POLICY "auth_all" ON email_triage FOR ALL USING (true);
CREATE POLICY "auth_all" ON financial_goals FOR ALL USING (true);
CREATE POLICY "auth_all" ON objectives FOR ALL USING (true);


-- ───────────────────────────────────────────────────────
-- INDEXES (performance)
-- ───────────────────────────────────────────────────────

CREATE INDEX IF NOT EXISTS idx_kanban_status ON kanban_tasks(status);
CREATE INDEX IF NOT EXISTS idx_kanban_position ON kanban_tasks(position);
CREATE INDEX IF NOT EXISTS idx_competitor_posts_handle ON competitor_posts(handle);
CREATE INDEX IF NOT EXISTS idx_competitor_posts_views ON competitor_posts(views DESC);
CREATE INDEX IF NOT EXISTS idx_client_posts_posted ON client_posts(posted_at DESC);
CREATE INDEX IF NOT EXISTS idx_content_ideas_status ON content_ideas(status);
CREATE INDEX IF NOT EXISTS idx_content_queue_status ON content_queue(status);
CREATE INDEX IF NOT EXISTS idx_email_triage_gmail_id ON email_triage(gmail_id);
CREATE INDEX IF NOT EXISTS idx_email_triage_priority ON email_triage(priority);
CREATE INDEX IF NOT EXISTS idx_financial_goals_month ON financial_goals(month);
CREATE INDEX IF NOT EXISTS idx_post_hooks_views ON post_hooks(views DESC);
